Resources:
  CdkLambdaHandlerServiceRole6D97282E:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkLambdaStack/CdkLambdaHandler/ServiceRole/Resource
  CdkLambdaHandlerAB0660C1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersb7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24S3Bucket94C5A060
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersb7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24S3VersionKeyB6FEC795
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersb7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24S3VersionKeyB6FEC795
      Role:
        Fn::GetAtt:
          - CdkLambdaHandlerServiceRole6D97282E
          - Arn
      Handler: index.handler
      Runtime: nodejs12.x
    DependsOn:
      - CdkLambdaHandlerServiceRole6D97282E
    Metadata:
      aws:cdk:path: CdkLambdaStack/CdkLambdaHandler/Resource
      aws:asset:path: /Users/issei-naruta/src/misc/lambda_test/cdk-lambda/lambda
      aws:asset:is-bundled: false
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zWOwQ7CIBBEv8U73bYxRo9aE8+mfsEKa0NbIGFBD4R/F2o8zZvN7M720B8P0O3O+OFGqqVN0nmC9AgoF3FhplBw0nYSV2c5+CiDuL7sHT0aCuSrGYld9JIql5TSQTubRT2ZVjRPhZBu0co6rpk/Z6HRQBrduq1WzYL3DdZahq29eBiiXCgMyJSzsE4RzNy++xN05fOZtW58tEEbgvGnXwsJsszWAAAA
    Metadata:
      aws:cdk:path: CdkLambdaStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersb7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24S3Bucket94C5A060:
    Type: String
    Description: S3 bucket for asset "b7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24"
  AssetParametersb7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24S3VersionKeyB6FEC795:
    Type: String
    Description: S3 key for asset version "b7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24"
  AssetParametersb7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24ArtifactHashF259107E:
    Type: String
    Description: Artifact hash for asset "b7bbe7582091c70fe634c6d934e58648a1697ab747b496bf06cf47f3d72b2e24"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

