version: "3.7"
services:
  jupyterlab:
    image: puyo
    volumes:
      - ./vol:/mnt/vol
      - ./home:/home/mirakui
    ports:
      - 8888:8888
    tty: true
    user: mirakui
    command: jupyter lab --ip=0.0.0.0 --no-browser
